### ISSUE TITLE
CLEANUP: Cache root directory ~/.cache/R.cache/?

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/R.cache#14]
On Linux, at least Ubuntu, the `~/.cache/` directory holds cache files for various software tools.  I don't think `~/.cache/` is an official Linux standard, but if it is a de facto standard, maybe we should have R.cache to make use of it as well?  If so, what should it be:
- `~/.cache/R/`
- `~/.cache/R/R.cache/`
- `~/.cache/R.cache/`

If this should be supported, it's probably best to have the same for all OSes (simplifies documentation).

Just a thought for now.

**Comment by xrobin** [comment]
I was going to open a bug about it. Cache stuff should go to `$XDG_CACHE_HOME` (if set) or `$HOME/.cache` otherwise. Please don't save into `$HOME/.cache` if `$XDG_CACHE_HOME` points somewhere else. I don't have a strong opinion about which of the 3 options you proposed exactly, I'd think the 3rd one is the most natural ($XDG_CACHE_HOME/R.cache/) but the others are fine too.

On Linux at least, this should allow you to get rid of the initial question ("The R.cache package needs to create a directory that will hold [...]").

**Comment by xrobin** [comment]
By the way I just remembered I should mention the [rappdirs](https://github.com/r-lib/rappdirs) package. It will select the correct folder across OSes.

**Comment by HenrikBengtsson** [comment]
Just a heads up, I'm working on adding support for OS-specific cache folders.

> On Linux at least, this should allow you to get rid of the initial question ("The R.cache package needs to create a directory that will hold [...]").

@xrobin, unfortunately we still have to adhere to the [CRAN Repository Policy](https://cran.r-project.org/web/packages/policies.html) which explicitly says:

- Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). [...]

This is the reason why R.cache (and other packages) needs to ask for the user's permission to write elsewhere.   One could argue that it should be allowed to also write to these OS-specific cache folders without having to ask for permission, but that is something we need to convince CRAN about.

**Comment by HenrikBengtsson** [comment]
Hi all, the next release attempts to acknowledge OS-specific cache folders.  Does the following look correct to you?

Version: 0.13.0-9000 [2019-03-26]

SIGNIFICANT CHANGES:

 * Now R.cache uses a default cache path that adheres to the standard cache
   location on the current operating system, whereas in previous versions it
   defaulted to ~/.Rcache.  On Unix, the 'XDG Base Directory Specification'
   is followed, which means that the R.cache folder will typically be
   ~/.cache/R/R.cache/.  On macOS, it will be ~/Library/Caches/R/R.cache/.
   On modern versions of Microsoft Windows, environment variables such
   as 'LOCALAPPDATA' will be used, which typically resolves to
   '%USERPROFILE%/AppData/Local, e.g. 'C:/Users/alice/AppData/Local'.
   If R.cache fails find a proper OS-specific cache folder, it will fall back
   to using ~/.Rcache as the previously done.
   Importantly, if ~/.Rcache already exists, then that will be used by
   default.  This is done in order to not loose previously cached files.
   Users with an existing folder who wish to move to the new standard need to
   move or remove the ~/.Rcache folder manually.

To try it out, install as
```r
remotes::install_github("HenrikBengtsson/R.cache@develop")
```

**Comment by xrobin** [comment]
Tested on Ubuntu 18.10 with R 3.5.3. It works perfectly fine: found my existing cache in ~/.Rcache, and once I removed it, it asked for permission to create a new cache in /mnt/data/cache (as requested by $XDG_CACHE_HOME). 
Thanks!
