### ISSUE TITLE
Problem with evalWithMemoization and knitr

### ISSUE THREAD

**Issue by skranz** [HenrikBengtsson/R.cache#15]
Dear Henrik,

there seems some quite subtle bug, that makes evalWithMemoization not work correctly when used inside an RMarkdown document and use RStudio's  Knit HTML. (At least on my computer).

I think the bug could be corrected by a simple change of line 42 in evalWithMemoization.R from the current:

``` r
key <- c(list(expr=expr), key);
```

to

``` r
key <- c(list(expr=as.character(expr)), key);
```

The problem is that when running Knit HTML the same substituted expression gets different digest codes (at least on my computer) and therefore it does not find a previously cached file. That does not happen when running the code just in the R console. The problem does not occur when using a character representation of expr. @yihui Maybe you also find this difference between knitting and directly running interesting.

Below is a screenshot of a knitted .Rmd file that illustrates the problem.

![image](https://cloud.githubusercontent.com/assets/1413022/19203166/134f076e-8cd6-11e6-8af6-a6e306d16337.png)

 Here is the .Rmd code

``````
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Digest - Knitr - Expression: Strange Behavior...

If you run the code chunk in R you always get the same digest.
If you say Knit HTML in RStudio the digest changes!
```{r}
library(digest)

f = function(expr) {
  substitute(expr)
}

# same digest in R, different ones with Knit HTML
digest(f({1}))
digest(f({1}))

f({1}) == f({1}) # TRUE
identical(f({1}), f({1})) # FALSE

```
``````

**Comment by HenrikBengtsson** [comment]
@skranz, thanks for reaching out.  Before anything else, how does R.cache and `evalWithMemoization()` come into play here?  AFAIK, knitr doesn't use R.cache.  Is there code you forgot to share?

**Comment by yihui** [comment]
I think this is irrelevant to R.cache. I'm not an expert to explain source references, but the difference seems to come from the source references when the code is evaluated in knitr:

```r
library(digest)

f = function(expr) {
  substitute(expr)
}
# same digest in R, different ones with Knit HTML
str(f({1}))
##  language {  1 }
##  - attr(*, "srcref")=List of 2
##   ..$ :Class 'srcref'  atomic [1:8] 7 7 7 7 7 7 7 7
##   .. .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##   ..$ :Class 'srcref'  atomic [1:8] 7 8 7 8 8 8 7 7
##   .. .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##  - attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##  - attr(*, "wholeSrcref")=Class 'srcref'  atomic [1:8] 1 0 7 9 0 9 1 7
##   .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0>
str(f({1}))
##  language {  1 }
##  - attr(*, "srcref")=List of 2
##   ..$ :Class 'srcref'  atomic [1:8] 8 7 8 7 7 7 8 8
##   .. .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##   ..$ :Class 'srcref'  atomic [1:8] 8 8 8 8 8 8 8 8
##   .. .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##  - attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0> 
##  - attr(*, "wholeSrcref")=Class 'srcref'  atomic [1:8] 1 0 8 9 0 9 1 8
##   .. ..- attr(*, "srcfile")=Classes 'srcfilecopy', 'srcfile' <environment: 0x7f86341b1ed0>
```

Unless you really need to do anything with the source references, it should be fairly safe to discard these attributes, i.e.

```r
f = function(expr) {
  res = substitute(expr)
  attributes(res) = NULL
  res
}
```

**Comment by skranz** [comment]
I encountered the problem because I wanted to use R.cache inside Rmd documents, not the default cache  functionality from knitr. (In particular R.cache was used in some function I defined early in a chunk and was called in later chunks). This is probably not a common use case, but I think it would be nice if evalWithMemoization could also be nicely used inside knitted code.

Consider the following simple example .Rmd file:

    In R the second call to evalWithMemoization yields the same result as the first but not when using Knit HTML.
    ```{r}
    library(R.cache)
    evalWithMemoization({runif(1)})
    evalWithMemoization({runif(1)})
    ```

With the following knitted HTML output.

![image](https://cloud.githubusercontent.com/assets/1413022/19210260/f6c13624-8d1d-11e6-8fb5-d7b6644ae845.png)

Thanks @yihui for pointing out the reason, why the two expressions differ! So an alternative solution would be simply to change line 42 of evalWithMemoization.R to the three-liner:
```r
key.expr = expr
attributes(key.expr) = NULL
key <- c(list(expr=key.expr), key);
```
I am not sure whether dropping all attributes may in some situations create problems when evaluating the expression. So copying expr to key.expr first seems safer.

**Comment by HenrikBengtsson** [comment]
Thxs. I understand; I'll look into how to best fix this without breaking other things.

**Comment by HenrikBengtsson** [comment]
I guess, better later than never.  I have fixed this in the develop branch by adding a new argument `drop` to `evalWithMemoization()`.  The default is `drop = c("srcref", "srcfile", "wholeSrcref")` which drops those attributes if set in `expr`.  A code chunk with:
```md
library(R.cache)
evalWithMemoization({runif(1)})
evalWithMemoization({runif(1)})
evalWithMemoization({runif(1)})
```   
will now produce identify output for all `evalWithMemoization({runif(1)})` calls.
