### ISSUE TITLE
enable / disable caching

### ISSUE THREAD

**Issue by dougmitarotonda** [HenrikBengtsson/R.cache#17]
My use case is that sometimes I want to run code without caching to match another machine’s environment as best as possible. What I am looking for is either a global variable / function parameter to `loadCache` and `saveCache` to allow me to toggle them on or off. 

I could `clearCache`, but that would delete everything, which is not what I want since I am usually running this on small sections of code. Deleting specific cached variables would be a pain since there are lots of variables.

I’ve looked through the documentation and don’t see anything to help me to do this - am I missing something? Or do you think this would be useful to add to your package? I can of course write my own wrappers around your functions to do this, but it seems better to have as a package feature.

(and thanks, I love the package!)

**Comment by HenrikBengtsson** [comment]
Good idea.  I'll see if I can add an `options()` for this.

FYI, when I had to "disable" this myself, I've temporarily renamed to cache root directory, e.g.
```sh
$ mv ~/.Rcache ~/.Rcache.HIDE
```

**Comment by dougmitarotonda** [comment]
Ah, that is a better workaround than writing wrappers, thanks for mentioning that - and for considering including this in the package!

**Comment by HenrikBengtsson** [comment]
R.cache 0.13.0 is now on CRAN.  It has an option `R.cache.enabled` making it possible to disable cache loading/saving.  See `?R.cache.options`.
