### ISSUE TITLE
Question: Caching saved across sessions

### ISSUE THREAD

**Issue by nadavrap** [HenrikBengtsson/R.cache#21]
R.cach is a useful package. But, I found that if I use it as part of a project, the cache is not retrieved in different sessions. I mean, I do set the caching path using `R.cache::setCacheRootPath`, but then when I call `evalWithMemoization` with the same `key`, It generates different files in different sessions, with different hash keys.
Is there an option so the generated hash will be the same across sessions?
I know I can use `pathname`, but it's less convenient.

**Comment by HenrikBengtsson** [comment]
Thanks.  The same key should generate the same hash / cache file name, so there should be no difference between sessions unless the function you memoize with `evalWithMemoization()` carry session-specific information (e.g. via a promise).

Having said that, I suspect this is related to https://github.com/HenrikBengtsson/R.cache/pull/19.  If I'm correct, this means that you would not see the problem with R 3.3.x, but in R (>= 3.4.0).  I understand what's going on, but I just haven't had time to set up tests etc to bring it in and release a new version.

You can test PR #19 by installing it as:
```r
remotes::install_github("HenrikBengtsson/R.cache#19")
```

**Comment by nadavrap** [comment]
Yes, it's seems to be related.
Thank you
