### ISSUE TITLE
Map NULL to empty file to consume zero memory instead of block size

### ISSUE THREAD

**Issue by lorenzwalthert** [HenrikBengtsson/R.cache#37]
I came across your package and thought it would be a good match to implement caching with styler in https://github.com/r-lib/styler/pull/538. A feature of the problem at hand is that there is no need to cache a specific value - the only thing we want to remember is *if* a computation has already been executed (in my case if the text to style has already been styled and hence does not need restyling). I could `R.cache::saveCache(object = NULL, key = text, ...)` or similar, but unfortunately, this will create a file with size > 0 bytes, and on my Mac, any file that is not totally empty takes 4KB of space beacuse that's the [block size](https://unix.stackexchange.com/questions/62049/why-are-text-files-4kb?newreg=ae91384e8e2f494b88e9fe6771ddbae0). In my usecase, it is likely that people will accumulate hundreds of cached values, which makes `R.cache::saveCache(object = NULL, ...)` a solution with too much overhead. 

For this reason, I propose to map `NULL` to an empty file, ~For this reasons, I propose to introduce an argument `shallow` (defaulting to `FALSE`) in `R.cache::saveCache()` (or to create another function for shallow hashing if you prefer)~. When set, a file with `base::file.create()` would be created that is completely empty to accommodate the case in which keys should be cached, but values are not needed. The advantage is that this will take 0 bytes on disk (ignoring some metadata like file name, permissions ect. stored somewhere else on the file system). We could use the current implementation of `R.cache::findCache()` without an error, other functions that expect meta data would probably need to be adapted but I believe we could easily identify if a cached value is `NULL`, just check if the file size is 0. I belive it is generic enough to have other applications than https://github.com/r-lib/styler/pull/538.

~You can find a basic implementation without tests and documentation [in my fork](https://github.com/lorenzwalthert/R.cache/commit/bb84959b53ba56cab2405a5d717565aa03d95914).~

**Comment by krlmlr** [comment]
Would it be easier to map `NULL` to empty files?

**Comment by lorenzwalthert** [comment]
Good idea, that's much more elegant I think.

**Comment by krlmlr** [comment]
@HenrikBengtsson: Do you think this is feasible? Would you consider a PR?

**Comment by HenrikBengtsson** [comment]
Thanks for the bump - this one slipped. Yes, I'm open to PRs. If just like to think thought that your needs are and what the options forward are.

**Comment by HenrikBengtsson** [comment]
I've just exported `generateCache()` in the develop branch;
```r
remotes::install_github("HenrikBengtsson/R.cache@develop")
```
This will allow you to generate cache pathnames without creating a file.  This will allow you to do things like:
```r
> pathname <- generateCache(key = list("foo"), dirs = c("styler", "this", "that"), suffix = ".styled")
> pathname
[1] "/home/hb/.cache/R/R.cache/styler/this/that/cfb1611e527451f9a3334e6f60768f5b.styled"
> already_styled <- utils::file_test("-f", pathname)
> already_styled
[1] FALSE
> res <- file.create(pathname)
> res
[1] TRUE
> utils::file_test("-f", pathname)
[1] TRUE
> file.size(pathname)
[1] 0
```

Would this be sufficient?

**Comment by lorenzwalthert** [comment]
It seems yes: https://github.com/r-lib/styler/pull/538/commits/36606a2a52828fcf959ee025e6e17e268b1253b9

Thanks.

**Comment by HenrikBengtsson** [comment]
Good to hear. FYI, I'll soon start preparing the next CRAN submission of R.cache (https://github.com/HenrikBengtsson/R.cache/milestone/4?closed=1)
