### ISSUE TITLE
Support for actively manage the cache

### ISSUE THREAD

**Issue by lorenzwalthert** [HenrikBengtsson/R.cache#46]
As the maintainer of {styler}, I got a warning that my package would be removed from CRAN:

```bash
This is not complying with the CRAN policy on use of ~/.cache by not cleaning up after itself:

% ls -lR ~/.cache/R/R.cache/styler/
... [some files in the cache]

It really must remove caches from earlier versions, and those which are empty or older than a week.
```
I don't know how to create cache file that have an expiry date, so the only way to do this would be to check my cache via  `.onLoad()` and remove certain files. Since all users of {R.cache} have the same problem with CRAN policies I assume, I thought I'd ask here if handling of this could be implemented here.

**Comment by HenrikBengtsson** [comment]
Would mind forwarding that email to me?  Contrary to this request, the CRAN policies do not mention anything about a maximum life-span on cached files.

For a solution, yes, clearing the cache at package load might be the best we can do.  The easiest would be to scan the specific package cache folder (here ~/.cache/R/R.cache/styler/) for files older than X days, where `X` can be controlled by an R option/env var, and that might be agile to whether or not `R CMD check` is running.  This would require calling `file.info()` on all files and filter by `ctime`.  I'm open for a PR/prototype function that does this.

I doubt I'll have time to get to this before your 14-day(?) deadline, and even if I would, it's unlikely that it would get implemented and available on CRAN in time.

**Comment by lorenzwalthert** [comment]
> Would mind forwarding that email to me? Contrary to this request, the CRAN policies do not mention anything about a maximum life-span on cached files.

I did. You are right, it's not explicit about the life span, I believe the relevant section is

> For R version 4.0 or later (hence a version dependency is required or only conditional use is possible), packages may store user-specific data, configuration and cache files in their respective user directories obtained from tools::R_user_dir(), provided that by default sizes are kept as small as possible and the contents are actively managed (including removing outdated material).


> I doubt I'll have time to get to this before your 14-day(?) deadline, and even if I would, it's unlikely that it would get implemented and available on CRAN in time.

The new deadline is Sept 25, so I did by no means mean I expect you do implement this. I will have to implement it myself for now I think, and how I did it is pretty much what you suggested.
