### ISSUE TITLE
Should `R.cache::generateCache()` and friends return only writable cache paths?

### ISSUE THREAD

**Issue by lorenzwalthert** [HenrikBengtsson/R.cache#47]
In {styler}, which uses {R.cache} as a backend, there was a recent [issue](https://github.com/r-lib/styler/issues/871) about the cache not being writable. Should `R.cache::generateCache()` (and friends) return a warning and a temporary cache path if the user path is not writable?

**Comment by lorenzwalthert** [comment]
Use the new capabilities of `file_test()` in R 4:

> Function file_test() in package utils gains tests for symlinks, readability and writability.

https://cran.r-project.org/doc/manuals/r-devel/NEWS.html. Not sure these changes are back-ported with {backports}.

**Comment by HenrikBengtsson** [comment]
1. See my comment/question https://github.com/r-lib/styler/issues/871#issuecomment-1086043697
2. **R.utils** has `Arguments$getWritablePath()` to check if a folder is writable. That can be used to assert write permissions

**Comment by HenrikBengtsson** [comment]
It turned out that `getCachePath()` already checked for write permissions, iff the cache folder did not already exist.  

I've now added that it also check for write permissions, if the folder already exists.  This is done once per R session for performance reasons.
